<a href="https://colab.research.google.com/github/MajoCarb/AmphoraProject/blob/master/main_secuencia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## AMPHORA CHALLENGE
#### By María José Carbajal Alonso

In [46]:
#importar librerias
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [56]:
#Ancestry file
ancestry_file = pd.read_csv('drive/MyDrive/Amphora/ancestry-1000genome.tsv', sep='\t')
#ancestry_file = pd.read_csv('ancestry-1000genome.tsv', sep='\t',index_col='Sample name')

#Superpopulation code dataframe
spp_code = pd.DataFrame()
spp_code['sample_name'] = ancestry_file['Sample name']

#getting the patients only
patients = spp_code['sample_name']

spp_code['superpopulation_code'] = ancestry_file['Superpopulation code']
spp_code.set_index('sample_name', inplace=True)

#getting the 5 categories we will use (ancestry types)
ancestry_types = list(spp_code['superpopulation_code'].unique())
cadena=""
for p in spp_code['superpopulation_code'][:10]:
  
  cadena = cadena+p
  print(cadena)

spp_code

AFR
AFRAFR
AFRAFRAFR
AFRAFRAFRAFR
AFRAFRAFRAFRAFR
AFRAFRAFRAFRAFRAFR
AFRAFRAFRAFRAFRAFRAFR
AFRAFRAFRAFRAFRAFRAFRAFR
AFRAFRAFRAFRAFRAFRAFRAFRAFR
AFRAFRAFRAFRAFRAFRAFRAFRAFRAFR


superpopulation_code
sample_name                     
NA19625                      AFR
NA19835                      AFR
NA19900                      AFR
NA19917                      AFR
NA19703                      AFR
...                          ...
NA19201                      AFR
NA19206                      AFR
NA19213                      AFR
NA19225                      AFR
NA19143                      AFR

[2504 rows x 1 columns]

In [51]:
#Reduction of number of patients using a sample of 10%, random state makes that the sample be the same 
#using 60% of data, takes 50 minutes to create de dataframe with the ancestry

patients_=patients.sample(frac=.1, random_state=1)
list(patients_.head(1).values)[0]
print(str(np.array(patients_[:5])))

['NA20876' 'HG01148' 'HG01366' 'HG01992' 'HG01851']


In [98]:
#Getting the patient's information in the CSV file 
patient = 'HG01851'
patient_x = pd.read_csv('drive/MyDrive/Amphora/Challenge_Samples/'+patient+'.csv')
patient_x.rename(columns={patient:'Presence'},inplace=True)
lenn= 20
#Creating the ALT and Presence lists (These will be the columns)    
alt_list= list(patient_x['ALT'])
alt_list=alt_list[:lenn]
presence_list = list(patient_x['Presence'])
presence_list=presence_list[:lenn]

str(presence_list)
secuencia = ("".join(map(str, presence_list)))
code = list(spp_code[spp_code.index==patient]['superpopulation_code'] )
code

afr_res = 1  if code[0] == 'AFR' else 0
eur_res = 1  if code[0] == 'EUR' else 0
asian_res = 1  if code[0] == 'SAS' or code[0] == 'EAS' else 0

data = [patient, code[0], secuencia, afr_res, eur_res, asian_res]
col = ['Patient', 'SPP_code', 'Sequence', 'AFR', 'EUR','ASIAN']

sample = {'Patient':patient, 'SPP_code':code[0], 'Sequence':secuencia, 'AFR':afr_res, 'EUR': eur_res,'ASIAN':asian_res}
data

df = pd.DataFrame(columns=col)
df=df.append(sample, ignore_index=True)
df.set_index('Patient')


SPP_code              Sequence AFR EUR ASIAN
Patient                                             
HG01851      EAS  00011000000110001110   0   0     1

In [119]:
#selecting some patients in order to reduce data
# patients_ = patients[426:449]
# patients_= patients_.append([patients[524:542], patients[920:938], patients[1028:1046]])
main_df = pd.DataFrame()
lenn= 10028 #total len = 10028 of chr:location list

for patient in patients_:

  
    


    patient_x = pd.read_csv('drive/MyDrive/Amphora/Challenge_Samples/'+patient+'.csv')
    patient_x.rename(columns={patient:'Presence'},inplace=True)
    
    #Creating the ALT and Presence lists (These will be the columns)    
    alt_list= list(patient_x['ALT'])
    alt_list=alt_list[:lenn]
    presence_list = list(patient_x['Presence'])
    presence_list=presence_list[:lenn]

    
    sequence = ("".join(map(str, presence_list)))
    code = list(spp_code[spp_code.index==patient]['superpopulation_code'] )
    code

    afr_res = 1  if code[0] == 'AFR' else 0
    eur_res = 1  if code[0] == 'EUR' else 0
    asian_res = 1  if code[0] == 'SAS' or code[0] == 'EAS' else 0

    data = [patient, code[0], sequence, afr_res, eur_res, asian_res]
    col = ['Patient', 'SPP_code', 'Sequence', 'AFR', 'EUR','ASIAN']

    sample = {'Patient':patient, 'SPP_code':code[0], 'Sequence':sequence, 'AFR':afr_res, 'EUR': eur_res,'ASIAN':asian_res}
    data

    df = pd.DataFrame(columns=col)
    df=df.append(sample, ignore_index=True)
    df.set_index('Patient')

    main_df = pd.concat([main_df,df], axis=0)

    

#patients_main_df=list(set(main_df.index.get_level_values('Patient')))
#spp_code_main_df=list(set(main_df.index.get_level_values('Superpopulation Code')))
main_df=main_df.set_index('Patient')



In [120]:
main_df

SPP_code                                           Sequence AFR EUR  \
Patient                                                                       
NA20876      SAS  0000101011011010111011100010000010100011101000...   0   0   
HG01148      AMR  0110100011011010111010000110000010100010110000...   0   0   
HG01366      AMR  0011100111011010111011000010000011100000110000...   0   0   
HG01992      AMR  0110100011111010111011000010001011101001101010...   0   0   
HG01851      EAS  0001100000011000111011000010000011000101101000...   0   0   
...          ...                                                ...  ..  ..   
NA19773      AMR  0100100001011000011011000010000011100101100010...   0   0   
HG01250      AMR  0010100011111010111010100001000011000010111000...   0   0   
NA18625      EAS  0001100000011010011010000010000011000101101010...   0   0   
NA18881      AFR  0010100001001010100010100110000011101000100100...   1   0   
HG01815      EAS  0100100000101011110011000010000011000011101010...   0   0   

        ASIAN  
Patient        
NA20876     1  
HG01148     0  
HG01366     0  
HG01992     0  
HG01851     1  
...       ...  
NA19773     0  
HG01250     0  
NA18625     1  
NA18881     0  
HG01815     1  

[250 rows x 5 columns]

In [103]:
print(main_df['ASIAN'].sum(),
main_df['AFR'].sum(),
main_df['EUR'].sum())

98 64 45


In [125]:
#main_df.xs('EUR',level='Superpopulation Code')
main_df.iloc[main_df.index.get_loc('NA19681')][1]
# main_df.index.names
#spp_code_main_df
#patients_main_df[:5]

'0'

In [26]:
main_df
ancestry_freq=main_df.index.get_level_values('Superpopulation Code').value_counts()//10028
ancestry_freq

AFR    64
EAS    55
EUR    45
SAS    43
AMR    43
Name: Superpopulation Code, dtype: int64

In [27]:
list(main_df.index.get_level_values('Superpopulation Code').unique())

['SAS', 'AMR', 'EAS', 'AFR', 'EUR']

In [3]:
#Saving the datafram into a CSV file at Google Drive
#main_df.to_csv('drive/MyDrive/Amphora/main_df_10%.csv', index=True)
df_without_index = pd.read_csv('drive/MyDrive/Amphora/main_df_10%.csv')
df_without_index
main_df = df_without_index
#main_df.set_index()

In [35]:
main_df

Patient Superpopulation Code Chr:Location ALT  Presence  EUR  AFR  \
0        NA20876                  SAS     5;195139   T         0    0    0   
1        NA20876                  SAS     5;336952   C         0    0    0   
2        NA20876                  SAS     5;389603   C         0    0    0   
3        NA20876                  SAS     5;851582   A         0    0    0   
4        NA20876                  SAS    5;1144802   C         1    0    0   
...          ...                  ...          ...  ..       ...  ...  ...   
2506995  HG01815                  EAS  22;49797810   A         1    0    0   
2506996  HG01815                  EAS  22;49855674   G         0    0    0   
2506997  HG01815                  EAS  22;50021013   A         0    0    0   
2506998  HG01815                  EAS  22;50258751   A         1    0    0   
2506999  HG01815                  EAS  22;50458664   C         0    0    0   

         ASIAN  
0            1  
1            1  
2            1  
3            1  
4            1  
...        ...  
2506995      1  
2506996      1  
2506997      1  
2506998      1  
2506999      1  

[2507000 rows x 8 columns]

## Here starts the section of training the model

In [4]:
from sklearn.model_selection import train_test_split
import numpy as np


In [5]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(main_df, test_size=0.2)
test
#train.sort_index()
#train.index.names[0]
train

Patient Superpopulation Code  Chr:Location ALT  Presence  EUR  AFR  \
819396   HG01095                  AMR  11;126446361   G         1    0    0   
262084   HG03077                  AFR   1;240095692   C         0    0    1   
1763058  NA19222                  AFR   7;133749550   A         0    0    1   
1933033  NA19649                  AMR  10;130413879   G         1    0    0   
2243148  NA20530                  EUR   11;76421615   G         0    1    0   
...          ...                  ...           ...  ..       ...  ...  ...   
1485047  NA12878                  EUR    1;81002264   A         0    1    0   
193133   HG01323                  AMR    2;23033710   G         0    0    0   
1113195  HG04019                  SAS    5;22655226   C         0    0    0   
1061073  HG00366                  EUR   7;124298853   C         1    1    0   
2155394  HG02725                  SAS   16;72276824   A         0    0    0   

         ASIAN  
819396       0  
262084       0  
1763058      0  
1933033      0  
2243148      0  
...        ...  
1485047      0  
193133       0  
1113195      1  
1061073      0  
2155394      1  

[2005600 rows x 8 columns]

In [15]:
main_df.index.names

FrozenList([None])

### European ancestry SVM

In [5]:
#Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [27]:
#drop the ancestries we are not going to predict
df_eur = main_df.drop(['ASIAN', 'AFR'], axis=1)

#df_eur = df_eur[df_eur['EUR']==1]

df_eur.set_index(['Patient'],inplace=True)
#df_eur
#len((set(df_eur.index.get_level_values('Patient'))))
patients_eur_df=list(set(df_eur.index.get_level_values('Patient')))
#len(patients_eur_df)

df_eur

Superpopulation Code Chr:Location ALT  Presence  EUR
Patient                                                     
NA20876                  SAS     5;195139   T         0    0
NA20876                  SAS     5;336952   C         0    0
NA20876                  SAS     5;389603   C         0    0
NA20876                  SAS     5;851582   A         0    0
NA20876                  SAS    5;1144802   C         1    0
...                      ...          ...  ..       ...  ...
HG01815                  EAS  22;49797810   A         1    0
HG01815                  EAS  22;49855674   G         0    0
HG01815                  EAS  22;50021013   A         0    0
HG01815                  EAS  22;50258751   A         1    0
HG01815                  EAS  22;50458664   C         0    0

[2507000 rows x 5 columns]

In [7]:
ohe = OneHotEncoder()
prueba =ohe.fit_transform(df_eur)
prueba

<2507000x10043 sparse matrix of type '<class 'numpy.float64'>'
	with 12535000 stored elements in Compressed Sparse Row format>

In [ ]:
print(prueba.toarray())

In [18]:
print(ohe.categories_[1])
spp_encoded = ohe.categories_[0]
chr_loc_encoded

['10;100090354' '10;100111214' '10;100176869' ... '9;99247758' '9;9978798'
 '9;99973992']


In [36]:
# Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string labels into numbers.
spp_encoded=le.fit_transform(df_eur['Superpopulation Code'])
chr_loc_encoded=le.fit_transform(df_eur['Chr:Location'])
alt_encoded=le.fit_transform(df_eur['ALT'])
print(set(list(alt_encoded)))

{0, 1, 2, 3, 4, 5, 6}


In [9]:
x = df_eur.drop(['EUR'],axis=1)
x = x.values
y = df_eur[['EUR']]
y = y.values
#y = column_or_1d(y, warn=True)
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, train_size=0.8,random_state=1)
#X_train.sort_values(by='Patient')
X_train



array([['AFR', '1;15185885', 'G', 1],
       ['EUR', '22;41537192', 'C', 0],
       ['EAS', '15;88736309', 'T', 0],
       ...,
       ['EUR', '22;28115498', 'T', 0],
       ['EAS', '5;129621590', 'C', 1],
       ['AMR', '7;3178549', 'A', 0]], dtype=object)

In [10]:
print(len(X_train))
X_train[0]

2005600


array(['AFR', '1;15185885', 'G', 1], dtype=object)

In [18]:
y_train.values.ravel()

array([0, 1, 0, ..., 1, 0, 0])

In [13]:
len(y_train.values.reshape(-1,))

2005600

In [16]:
np.ravel(y_train)

array([0, 1, 0, ..., 1, 0, 0])

In [11]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors=2)

In [12]:
knn_model.fit(X_train,np.ravel(y_train))

ValueError: ignored

In [ ]:
# Use the knn_model's predict method on the test data
y_pred = knn_model.predict(X_test)
y_pred

In [46]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Use the forest's predict method on the test data

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

# Model Precision: what percentage of positive tuples are labeled as such?
print("Precision:",metrics.precision_score(y_test, y_pred))

# Model Recall: what percentage of positive tuples are labelled as such?
print("Recall:",metrics.recall_score(y_test, y_pred))

ValueError: ignored

In [ ]:

y_test.value_counts()

EUR
0      398
1      102
dtype: int64

In [ ]:
ancestry_freq=df_eur.index.get_level_values('Superpopulation Code').value_counts()//10
ancestry_freq

AFR    64
EAS    55
EUR    45
SAS    43
AMR    43
Name: Superpopulation Code, dtype: int64

In [ ]:
#IMPORTANT: first argument is true values, second argument is predicted values
# this produces a 2x2 numpy array (matrix)
print(metrics.confusion_matrix(y_test, y_pred))

[[398   0]
 [102   0]]


In [ ]:
confusion = metrics.confusion_matrix(y_test, y_pred)
print(confusion)
#[row, column]
TP = confusion[1, 1]
TN = confusion[0, 0]
FP = confusion[0, 1]
FN = confusion[1, 0]

[[398   0]
 [102   0]]


In [ ]:


# use float to perform true division, not integer division
print((TP + TN) / float(TP + TN + FP + FN))
print(metrics.accuracy_score(y_test, y_pred))



0.796
0.796


In [ ]:
#Sensitivity: When the actual value is positive, how often is the prediction correct?

sensitivity = TP / float(FN + TP)

print(sensitivity)
print(metrics.recall_score(y_test, y_pred))



0.0
0.0


In [ ]:
precision = TP / float(TP + FP)

print(precision)
print(metrics.precision_score(y_test, y_pred))

nan
0.0


c:\Users\Majo Carbajal\anaconda3\envs\amphora\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
c:\Users\Majo Carbajal\anaconda3\envs\amphora\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
