
## AMPHORA CHALLENGE
### By María José Carbajal Alonso

* Import libraries

In [35]:
#importar librerias
import pandas as pd
import numpy as np
#from google.colab import drive
#drive.mount('/content/drive')

In [36]:
#Ancestry file
#ancestry_file = pd.read_csv('drive/MyDrive/Amphora/ancestry-1000genome.tsv', sep='\t')
ancestry_file = pd.read_csv('ancestry-1000genome.tsv', sep='\t')

#Superpopulation code dataframe
spp_code = pd.DataFrame()
spp_code['sample_name'] = ancestry_file['Sample name']

#getting only the patients 
patients = spp_code['sample_name']

spp_code['superpopulation_code'] = ancestry_file['Superpopulation code']
spp_code.set_index('sample_name', inplace=True)

#getting the 5 categories we will use (ancestry types)
ancestry_types = list(spp_code['superpopulation_code'].unique())

spp_code



superpopulation_code
sample_name                     
NA19625                      AFR
NA19835                      AFR
NA19900                      AFR
NA19917                      AFR
NA19703                      AFR
...                          ...
NA19201                      AFR
NA19206                      AFR
NA19213                      AFR
NA19225                      AFR
NA19143                      AFR

[2504 rows x 1 columns]

In [37]:
#Reduction of number of patients using a sample of 100%, random state makes that the sample be the same 

patients_=patients.sample(frac=1, random_state=1)
list(patients_.head(1).values)[0]
print(str(np.array(patients_[:5])))
len(patients_)

['NA20876' 'HG01148' 'HG01366' 'HG01992' 'HG01851']


2504

In [38]:
main_df = pd.DataFrame()
lenn= 10028 #total len = 10028 of chr:location list

for patient in patients_:   

    #Getting the patient's information fron its CSV file
    #patient_x = pd.read_csv('drive/MyDrive/Amphora/Challenge_Samples/'+patient+'.csv')
    patient_x = pd.read_csv('Challenge_Samples/'+patient+'.csv')
    patient_x.rename(columns={patient:'Presence'},inplace=True)
    
    #Creating Presence list    
    presence_list = list(patient_x['Presence'])
    presence_list=presence_list[:lenn]

    #Creating a string value that contains all the information of Chr:Location, ALT and Presence
    sequence = ("".join(map(str, presence_list)))

    #Getting the Superpopulation Code 
    code = list(spp_code[spp_code.index==patient]['superpopulation_code'] )
    code = code[0]

    #Getting the values for the three nationalities we're going to predict
    
    afr_res = 1  if code == 'AFR' else 0
    eur_res = 1  if code == 'EUR' else 0
    asian_res = 1  if code == 'SAS' or code == 'EAS' else 0

    #creating the data and the columns of the dataframe
    data = [patient, code, sequence, afr_res, eur_res, asian_res]
    col = ['Patient', 'SPP_code', 'Sequence', 'AFR', 'EUR','ASIAN']

    
    sample = {'Patient':patient, 'SPP_code':code, 'Sequence':sequence, 'AFR':afr_res, 'EUR': eur_res,'ASIAN':asian_res}
    data

    df = pd.DataFrame(columns=col)
    df=df.append(sample, ignore_index=True)
    df.set_index('Patient')

    main_df = pd.concat([main_df,df], axis=0)

    

#patients_main_df=list(set(main_df.index.get_level_values('Patient')))
#spp_code_main_df=list(set(main_df.index.get_level_values('Superpopulation Code')))
main_df=main_df.set_index('Patient')

In [60]:
main_df

Patient SPP_code                                           Sequence  \
0     NA20876      SAS  0000101011011010111011100010000010100011101000...   
1     HG01148      AMR  0110100011011010111010000110000010100010110000...   
2     HG01366      AMR  0011100111011010111011000010000011100000110000...   
3     HG01992      AMR  0110100011111010111011000010001011101001101010...   
4     HG01851      EAS  0001100000011000111011000010000011000101101000...   
...       ...      ...                                                ...   
2499  NA20901      SAS  0101110011011010110001100110000011110111111000...   
2500  HG02861      AFR  0011100001111110101000100110000011001011110000...   
2501  NA18637      EAS  0100100000011000111011000010000001000101101000...   
2502  HG03809      SAS  0101110011001010111011100010000011110011111000...   
2503  NA18557      EAS  0000100010101000011011100010000001000011100010...   

      AFR  EUR  ASIAN  
0       0    0      1  
1       0    0      0  
2       0    0      0  
3       0    0      0  
4       0    0      1  
...   ...  ...    ...  
2499    0    0      1  
2500    1    0      0  
2501    0    0      1  
2502    0    0      1  
2503    0    0      1  

[2504 rows x 6 columns]

In [61]:
print(main_df['ASIAN'].sum(),
main_df['AFR'].sum(),
main_df['EUR'].sum())

993 661 503


In [62]:
#Saving the dataframe into a CSV file at Google Drive or locally
#main_df.to_csv('drive/MyDrive/Amphora/main_df_100%_seq.csv', index=True)
#main_df.to_csv('main_df_100%_seq.csv', index=True)
#df_from_file = pd.read_csv('drive/MyDrive/Amphora/main_df_100%_seq.csv')
df_from_file = pd.read_csv('main_df_100%_seq.csv')

main_df = df_from_file
#main_df.set_index()

In [63]:
main_df

Patient SPP_code                                           Sequence  \
0     NA20876      SAS  0000101011011010111011100010000010100011101000...   
1     HG01148      AMR  0110100011011010111010000110000010100010110000...   
2     HG01366      AMR  0011100111011010111011000010000011100000110000...   
3     HG01992      AMR  0110100011111010111011000010001011101001101010...   
4     HG01851      EAS  0001100000011000111011000010000011000101101000...   
...       ...      ...                                                ...   
2499  NA20901      SAS  0101110011011010110001100110000011110111111000...   
2500  HG02861      AFR  0011100001111110101000100110000011001011110000...   
2501  NA18637      EAS  0100100000011000111011000010000001000101101000...   
2502  HG03809      SAS  0101110011001010111011100010000011110011111000...   
2503  NA18557      EAS  0000100010101000011011100010000001000011100010...   

      AFR  EUR  ASIAN  
0       0    0      1  
1       0    0      0  
2       0    0      0  
3       0    0      0  
4       0    0      1  
...   ...  ...    ...  
2499    0    0      1  
2500    1    0      0  
2501    0    0      1  
2502    0    0      1  
2503    0    0      1  

[2504 rows x 6 columns]

##  Here starts the section of training the models

In [65]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier

def createLabelEncoder(df):
    #creating labelEncoder
    le = preprocessing.LabelEncoder()
    # Converting string labels into numbers.
    seq_encoded=le.fit_transform(df['Sequence'])

    #print(set(list(seq_encoded)))
    type(seq_encoded)
    list(le.classes_)

    return seq_encoded

In [96]:
#Let's CREATE A FUNCTION to preprocess the data of sequence in order to have an int value to fit the model

# Import LabelEncoder
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

def createLabelEncoder(df):
    #creating labelEncoder
    le = preprocessing.LabelEncoder()
    # Converting string labels into numbers.
    seq_encoded=le.fit_transform(df['Sequence'])

    #print(set(list(seq_encoded)))
    type(seq_encoded)
    list(le.classes_)

    return seq_encoded

#function for any model

def modelData(df, modelClass):
    



    seq_encoded = createLabelEncoder(df)

    # Declare X and y variables
    x= seq_encoded
    x = x.reshape(-1, 1)
    y = df[[df.columns[2]]].values
    


    X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, train_size=0.8,random_state=1)

    if modelClass == 'knn':
        model = KNeighborsClassifier()
        print('MODEL CHOSEN: KNN\n')
    elif modelClass == 'gnb':
        model = GaussianNB()
        print('MODEL CHOSEN: Naive Bayes\n')
    elif modelClass == 'rfc':
        model = RandomForestClassifier()
        print('MODEL CHOSEN: Random Forest\n')
    elif modelClass == 'logreg':
        model = RandomForestClassifier()
        print('MODEL CHOSEN: Logistic Regression\n')

            
    cv_scores = cross_val_score(model, X_train,np.ravel(y_train), cv=10,scoring='accuracy')

    model.fit(X_train, y_train.ravel())

    #Predict the response for test dataset
    y_pred=model.predict(X_test)


    # print the first 10 predicted probabilities of class membership
    y_pred_prob=model.predict_proba(X_test)

    print(metrics.confusion_matrix(y_test, y_pred))

    # Model Precision: what percentage of positive tuples are labeled as such?
    print("Precision:",metrics.precision_score(y_test, y_pred))

    # Model Recall: what percentage of positive tuples are labelled as such?
    print("Recall:",metrics.recall_score(y_test, y_pred))

    # Model Accuracy: how often is the classifier correct?
    print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

    print('Acuracy cv_scores mean:{}'.format(np.mean(cv_scores)))

    # IMPORTANT: first argument is true values, second argument is predicted probabilities
    print("AUC: ",metrics.roc_auc_score(y_test, y_pred_prob[:, 1]))

    print("cross-validated AUC: ",cross_val_score(rfc, X_train,np.ravel(y_train), cv=10,scoring='roc_auc').mean(),'\n')



### **European ancestry KNN**

In [97]:
#drop the ancestries we are not going to predict
df_eur = main_df.drop(['ASIAN', 'AFR'], axis=1)
df_eur.set_index(['Patient'],inplace=True)
patients_eur_df=list(set(df_eur.index.get_level_values('Patient')))
#len(patients_eur_df)

modelData(df_eur, 'knn')
modelData(df_eur, 'logreg')
modelData(df_eur, 'gnb')
modelData(df_eur, 'rfc')

MODEL CHOSEN: KNN

[[350  43]
 [ 68  40]]
Precision: 0.4819277108433735
Recall: 0.37037037037037035
Accuracy: 0.7784431137724551
Acuracy cv_scores mean:0.78531592039801
AUC:  0.7651847139760626
cross-validated AUC:  0.7596350720158466 

MODEL CHOSEN: Logistic Regression

[[332  61]
 [ 65  43]]
Precision: 0.41346153846153844
Recall: 0.39814814814814814
Accuracy: 0.7485029940119761
Acuracy cv_scores mean:0.772318407960199
AUC:  0.7602252379606069
cross-validated AUC:  0.7585363600394172 

MODEL CHOSEN: Naive Bayes

[[393   0]
 [108   0]]
Precision: 0.0
Recall: 0.0
Accuracy: 0.7844311377245509
Acuracy cv_scores mean:0.8027985074626866
AUC:  0.6635331260013193


c:\Users\Majo Carbajal\anaconda3\envs\amphora\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


cross-validated AUC:  0.7579993418040293 

MODEL CHOSEN: Random Forest

[[332  61]
 [ 66  42]]
Precision: 0.4077669902912621
Recall: 0.3888888888888889
Accuracy: 0.7465069860279441
Acuracy cv_scores mean:0.772318407960199
AUC:  0.755089058524173
cross-validated AUC:  0.7623791942885012 



### **African ancestry**

In [98]:
#drop the ancestries we are not going to predict
df_afr = main_df.drop(['EUR', 'ASIAN'], axis=1)
df_afr.set_index(['Patient'],inplace=True)
patients_afr_df=list(set(df_afr.index.get_level_values('Patient')))
#len(patients_eur_df)

modelData(df_afr, 'logreg')
modelData(df_afr, 'knn')
modelData(df_afr, 'gnb')
modelData(df_afr, 'rfc')
df_afr

MODEL CHOSEN: Logistic Regression

[[340  25]
 [ 33 103]]
Precision: 0.8046875
Recall: 0.7573529411764706
Accuracy: 0.8842315369261478
Acuracy cv_scores mean:0.8861865671641791
AUC:  0.9121877518130539
cross-validated AUC:  0.9381258545763262 

MODEL CHOSEN: KNN

[[348  17]
 [ 28 108]]
Precision: 0.864
Recall: 0.7941176470588235
Accuracy: 0.9101796407185628
Acuracy cv_scores mean:0.8931815920398011
AUC:  0.9140410958904108
cross-validated AUC:  0.9367053090604303 

MODEL CHOSEN: Naive Bayes

[[365   0]
 [136   0]]
Precision: 0.0
Recall: 0.0
Accuracy: 0.7285429141716567
Acuracy cv_scores mean:0.7378955223880597
AUC:  0.8936140209508461


c:\Users\Majo Carbajal\anaconda3\envs\amphora\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


cross-validated AUC:  0.9402232699065584 

MODEL CHOSEN: Random Forest

[[340  25]
 [ 33 103]]
Precision: 0.8046875
Recall: 0.7573529411764706
Accuracy: 0.8842315369261478
Acuracy cv_scores mean:0.8856890547263682
AUC:  0.9095588235294118
cross-validated AUC:  0.9388696170030402 



SPP_code                                           Sequence  AFR
Patient                                                                 
NA20876      SAS  0000101011011010111011100010000010100011101000...    0
HG01148      AMR  0110100011011010111010000110000010100010110000...    0
HG01366      AMR  0011100111011010111011000010000011100000110000...    0
HG01992      AMR  0110100011111010111011000010001011101001101010...    0
HG01851      EAS  0001100000011000111011000010000011000101101000...    0
...          ...                                                ...  ...
NA20901      SAS  0101110011011010110001100110000011110111111000...    0
HG02861      AFR  0011100001111110101000100110000011001011110000...    1
NA18637      EAS  0100100000011000111011000010000001000101101000...    0
HG03809      SAS  0101110011001010111011100010000011110011111000...    0
NA18557      EAS  0000100010101000011011100010000001000011100010...    0

[2504 rows x 3 columns]

In [91]:
seq_encoded = createLabelEncoder(df_afr)

# Declare X and y variables
x= seq_encoded
x1D = seq_encoded
x = x.reshape(-1, 1)
y = df_afr[['AFR']]
y = y.values
#y = df_afr[df_afr.columns[2]].values


X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, train_size=0.8,random_state=1)
#X_train.sort_values(by='Patient')
len(y_train)
len(seq_encoded)
x

array([[ 179],
       [2306],
       [1210],
       ...,
       [1418],
       [2193],
       [ 124]])

In [79]:
#y = df_afr[df_afr.columns[2]].values
#df_afr[[2]].values
y

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int64)

In [92]:
# import the class
from sklearn.naive_bayes import GaussianNB


# instantiate the model (using the default parameters)
gnb = GaussianNB()
cv_scores = cross_val_score(gnb, X_train,np.ravel(y_train), cv=10,scoring='accuracy')

# fit the model with data
gnb.fit(X_train, np.ravel(y_train))

#Predict the response for test dataset
y_pred=gnb.predict(X_test)


# print the first 10 predicted probabilities of class membership
y_pred_prob=gnb.predict_proba(X_test)
print("Predicted probabilities",y_pred_prob)

cv_scores


Predicted probabilities [[8.79706314e-01 1.20293686e-01]
 [7.81652153e-01 2.18347847e-01]
 [9.99356611e-01 6.43389120e-04]
 ...
 [8.42203416e-01 1.57796584e-01]
 [9.89224798e-01 1.07752021e-02]
 [6.95784439e-01 3.04215561e-01]]


array([0.73631841, 0.73631841, 0.73631841, 0.74      , 0.74      ,
       0.74      , 0.74      , 0.74      , 0.735     , 0.735     ])

In [95]:
from sklearn.linear_model import LogisticRegression
reg = LogisticRegression()
reg.fit(X_train, y_train)
y_pred = reg.predict(X_test)
y_pred_prob=reg.predict_proba(X_test)
print("Predicted probabilities",y_pred_prob)


c:\Users\Majo Carbajal\anaconda3\envs\amphora\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Predicted probabilities [[0.80595955 0.19404045]
 [0.78245768 0.21754232]
 [0.88828109 0.11171891]
 ...
 [0.79652341 0.20347659]
 [0.85605724 0.14394276]
 [0.58468199 0.41531801]]


In [77]:
np.ravel(y_train)
y_train

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [93]:
print(metrics.confusion_matrix(y_test, y_pred))

[[365   0]
 [136   0]]


In [51]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Use the forest's predict method on the test data

# Model Precision: what percentage of positive tuples are labeled as such?
print("Precision:",metrics.precision_score(y_test, y_pred))

# Model Recall: what percentage of positive tuples are labelled as such?
print("Recall:",metrics.recall_score(y_test, y_pred))

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

print('Acuracy cv_scores mean:{}'.format(np.mean(cv_scores)))

Precision: 0.0
Recall: 0.0
Accuracy: 0.7285429141716567
Acuracy cv_scores mean:0.7378955223880597


c:\Users\Majo Carbajal\anaconda3\envs\amphora\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [52]:
#AUC

# IMPORTANT: first argument is true values, second argument is predicted probabilities
print(metrics.roc_auc_score(y_test, y_pred_prob[:, 1]))

print("cross-validated AUC: ",cross_val_score(gnb, X_train,np.ravel(y_train), cv=10,scoring='roc_auc').mean())

0.8936140209508461
cross-validated AUC:  0.8966706480183569


### **Asian ancestry Random forest**

In [53]:
#drop the ancestries we are not going to predict
df_asian = main_df.drop(['AFR', 'EUR'], axis=1)
df_asian.set_index(['Patient'],inplace=True)
patients_asian_df=list(set(df_asian.index.get_level_values('Patient')))
#len(patients_eur_df)

df_asian

SPP_code                                           Sequence  ASIAN
Patient                                                                   
NA20876      SAS  0000101011011010111011100010000010100011101000...      1
HG01148      AMR  0110100011011010111010000110000010100010110000...      0
HG01366      AMR  0011100111011010111011000010000011100000110000...      0
HG01992      AMR  0110100011111010111011000010001011101001101010...      0
HG01851      EAS  0001100000011000111011000010000011000101101000...      1
...          ...                                                ...    ...
NA20901      SAS  0101110011011010110001100110000011110111111000...      1
HG02861      AFR  0011100001111110101000100110000011001011110000...      0
NA18637      EAS  0100100000011000111011000010000001000101101000...      1
HG03809      SAS  0101110011001010111011100010000011110011111000...      1
NA18557      EAS  0000100010101000011011100010000001000011100010...      1

[2504 rows x 3 columns]

In [99]:
modelData(df_asian, 'logreg')
modelData(df_asian, 'knn')
modelData(df_asian, 'gnb')
modelData(df_asian, 'rfc')

MODEL CHOSEN: Logistic Regression

[[233  69]
 [ 73 126]]
Precision: 0.6461538461538462
Recall: 0.6331658291457286
Accuracy: 0.716566866267465
Acuracy cv_scores mean:0.7234129353233831
AUC:  0.800434290658591
cross-validated AUC:  0.8030138024374933 

MODEL CHOSEN: KNN

[[252  50]
 [ 72 127]]
Precision: 0.7175141242937854
Recall: 0.6381909547738693
Accuracy: 0.7564870259481038
Acuracy cv_scores mean:0.7518706467661692
AUC:  0.8074395154580851
cross-validated AUC:  0.8017391185662726 

MODEL CHOSEN: Naive Bayes

[[292  10]
 [179  20]]
Precision: 0.6666666666666666
Recall: 0.10050251256281408
Accuracy: 0.6227544910179641
Acuracy cv_scores mean:0.6425124378109454
AUC:  0.5472727877799594
cross-validated AUC:  0.8043515714902186 

MODEL CHOSEN: Random Forest

[[233  69]
 [ 73 126]]
Precision: 0.6461538461538462
Recall: 0.6331658291457286
Accuracy: 0.716566866267465
Acuracy cv_scores mean:0.7234129353233831
AUC:  0.795201171420014
cross-validated AUC:  0.8023257662935455 



In [54]:
seq_encoded = createLabelEncoder(df_asian)

# Declare X and y variables
x= seq_encoded
x1D = seq_encoded
x = x.reshape(-1, 1)
y = df_asian[['ASIAN']]
y = y.values
y = np.array(df_asian[['ASIAN']])


X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, train_size=0.8,random_state=1)
#X_train.sort_values(by='Patient')
type(y)


numpy.ndarray

In [55]:
type(df_asian.iloc[:,2])
type(np.array(df_asian.iloc[:,2]))

numpy.ndarray

In [56]:
# import the class
from sklearn.ensemble import RandomForestClassifier

# instantiate the model (using the default parameters)
rfc = RandomForestClassifier()
cv_scores = cross_val_score(rfc, X_train,np.ravel(y_train), cv=10,scoring='accuracy')

# fit the model with data
rfc.fit(X_train, y_train.ravel())

#Predict the response for test dataset
y_pred=rfc.predict(X_test)


# print the first 10 predicted probabilities of class membership
y_pred_prob=rfc.predict_proba(X_test)
print("Predicted probabilities",y_pred_prob)



Predicted probabilities [[0.75 0.25]
 [0.26 0.74]
 [0.33 0.67]
 ...
 [0.73 0.27]
 [0.18 0.82]
 [0.93 0.07]]


In [57]:
print(metrics.confusion_matrix(y_test, y_pred))

[[233  69]
 [ 73 126]]


In [58]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Use the forest's predict method on the test data
# Model Precision: what percentage of positive tuples are labeled as such?
print("Precision:",metrics.precision_score(y_test, y_pred))

# Model Recall: what percentage of positive tuples are labelled as such?
print("Recall:",metrics.recall_score(y_test, y_pred))

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

print('Acuracy cv_scores mean:{}'.format(np.mean(cv_scores)))

Precision: 0.6461538461538462
Recall: 0.6331658291457286
Accuracy: 0.716566866267465
Acuracy cv_scores mean:0.7234129353233831


In [59]:
#AUC

# IMPORTANT: first argument is true values, second argument is predicted probabilities
print(metrics.roc_auc_score(y_test, y_pred_prob[:, 1]))

print("cross-validated AUC: ",cross_val_score(rfc, X_train,np.ravel(y_train), cv=10,scoring='roc_auc').mean())

0.8070068887483776
cross-validated AUC:  0.8007290081119015
